- name: add keys for nginx repo
  apt_key:
    url: 'https://nginx.org/keys/nginx_signing.key'
    state: present

- name: add repositories for nginx
  apt_repository:
    repo: '{{ item.value.repo }}'
  with_dict: '{{ nginx.repos }}'

- name: install nginx packages
  yum:
    name: '{{ nginx.packages }}'
    state: latest
    update_cache: yes
